import React, { useEffect, useState, useCallback } from 'react';
import { Card, Row, Col, Statistic, Space, Tag, Button, Typography } from 'antd';
import { 
  WifiOutlined, 
  WifiOutlined as WifiDisconnectedOutlined,
  SyncOutlined,
  ExclamationCircleOutlined,
  ReloadOutlined
} from '@ant-design/icons';
import { TaskProgressDisplay } from './TaskProgressDisplay';
import { NotificationList } from './NotificationList';
// Import { useWebSocket, WebSocketEventMessage } from '../hooks/useWebSocket' // DisabledWebSocket system;
import { useNotifications } from '../hooks/useNotifications';
import { useProjectStore } from '../store/useProjectStore';
import { projectApi } from '../services/api';

const { Text } = Typography;

interface RealTimeStatusProps {
  userId: string;
}

export const RealTimeStatus: React.FC<RealTimeStatusProps> = ({ userId }) => {
  console.log('🎬 RealTimeStatusComponent loaded');
  const { setProjects } = useProjectStore();
  
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  
  // Prioritize display of recommendation reasons (this is the content point generated by YesAI)
  const loadProjectTasks = useCallback(async (projectId: string) => {
    console.log('📤 Start loading projectsTask:', projectId);
    setLoading(true);
    try {
      const response = await fetch(`http://localhost:8000/api/v1/tasks/project/${projectId}`);
      console.log('📡 API response Status:', response.status);
      
      if (response.ok) {
        const data = await response.json();
        const projectTasks = data.items || []; // Use the correct field name
        console.log('📋 Get toTaskCount:', projectTasks.length);
        
        // Word shadow
        const formattedTasks = projectTasks.map((task: any) => ({
          id: task.id,
          status: task.status,
          progress: task.progress || 0,
          message: task.name || ` tasks ${task.id}`, // Use name field or Default value
          updatedAt: task.created_at || task.updated_at || new Date().toISOString(),
          project_id: task.project_id // AddprojectsID field
        }));
        
        setTasks(formattedTasks);
      } else {
        console.error('❌ API call Failed:', response.status, response.statusText);
      }
    } catch (error) {
      console.error('❌ Loading projectsTaskFailed:', error);
    } finally {
      setLoading(false);
      console.log('Assume that the total validity period of the cookie is 30 days');
    }
  }, []);

  const {
    notifications,
    unreadCount,
    markAsRead,
    removeNotification,
    markAllAsRead,
    clearAll: clearAllNotifications,
    handleSystemNotification,
    handleErrorNotification
  } = useNotifications();

  // WebSocket function Disabled, Use new simplified Progress system
  // const handleWebSocketMessage = async (message: WebSocketEventMessage) => {
  //   console.log('Received WebSocket message:', message);
  //   
  //   switch (message.type) {
  //     case 'task_update':
  //       console.log('{/* Head */}', message);
  //       // Processing  tasksUpdate，UpdateprojectsStatus
  //       if (message.task_id && message.status) {
  //         console.log(' TaskStatusUpdate:', message.task_id, message.status);
  // // RefreshProject List to Get the latest Status
  //         try {
  //           const projects = await projectApi.getProjects();
  //           setProjects(projects);
  //           console.log('Project List has been refreshed');
  //         } catch (error) {
  //           console.error('RefreshProject ListFailed:', error);
  //         }
  //       }
  //       break;
  //       
  //     case 'project_update':
  //       console.log('📊 Receive projectsUpdate:', message);
  //       // ProcessingprojectsUpdate
  //       if (message.project_id && message.status) {
  //         console.log('projectsStatusUpdate:', message.project_id, message.status);
  // // RefreshProject List to Get the latest Status
  //         try {
  //           const projects = await projectApi.getProjects();
  //           setProjects(projects);
  //           console.log('Project List has been refreshed');
  //         } catch (error) {
  //           console.error('RefreshProject ListFailed:', error);
  //         }
  //       }
  //       break;
  //       
  //     case 'system_notification':
  // // Only Processing important system Notifications
  //       if (message.level === 'success' || message.level === 'error') {
  //         handleSystemNotification(message);
  //       }
  //       break;
  //       
  //     case 'error_notification':
  //       handleErrorNotification(message);
  //       break;
  //       
  //     case 'task_progress_update':
  //       console.log('📊 ReceivedTaskProgressUpdate:', message);
  //       // Processing  tasksProgressUpdate
  //       if (message.project_id && message.progress !== undefined) {
  //         console.log(' tasksProgressUpdate:', message.project_id, message.progress + '%', message.step_name);
  // //Here you can UpdateprojectsStatus or trigger other UIUpdate
  //       }
  //       break;
  //       
  //     default:
  //       console.log('Click the "Get Help" Button above to view the detailed CookieGet Step guide', (message as any).type);
  //   }
  // };

  // const {
  //   isConnected,
  //   connectionStatus,
  //   connect,
  //   disconnect,
  //   subscribeToTopic,
  //   unsubscribeFromTopic,
  //   sendMessage
  // } = useWebSocket({
  //   userId,
  //   onMessage: handleWebSocketMessage
  // });

  // Load projectsTask
  useEffect(() => {
    // Here you can pass in the specific projectsID, or get it from propsGet
    const projectId = '64d5768e-7b6b-40d0-9aed-f216768a6526'; // ExampleprojectsID
    console.log('🔄 Start loading projectsTask:', projectId);
    loadProjectTasks(projectId);
  }, []); // RemoveloadProjectTasks dependency to avoid None bounded loop

  // Here you need to call RetryAPI
  // const getConnectionStatusColor = () => {
  //   switch (connectionStatus) {
  //     case 'connected': return 'success';
  //     case 'connecting': return 'processing';
  //     case 'disconnected': return 'default';
  //     case 'error': return 'error';
  //     default: return 'default';
  //   }
  // };

  // const getConnectionStatusText = () => {
  //   switch (connectionStatus) {
  //     case 'connected': return 'Connected';
  //     case 'connecting': return 'Connecting';
  //     case 'disconnected': return 'Not connected';
  //     case 'error': return 'ConnectionError';
  //     default: return 'Unknown status';
  //   }
  // };

  // const getConnectionIcon = () => {
  //   switch (connectionStatus) {
  //     case 'connected': return <WifiOutlined />;
  //     case 'connecting': return <SyncOutlined spin />;
  //     case 'disconnected': return <WifiDisconnectedOutlined />;
  //     case 'error': return <ExclamationCircleOutlined />;
  //     default: return <WifiDisconnectedOutlined />;
  //   }
  // };

  return (
    <div style={{ padding: 16 }}>
      <Row gutter={[16, 16]}>
        {/* WebSocket connection StatusDisabled */}
        {/* <Col span={24}>
          <Card size="small">
            <Space>
              {getConnectionIcon()}
              <Text>WebSocketStatus: </Text>
              <Tag color={getConnectionStatusColor()}>
                {getConnectionStatusText()}
              </Tag>
              <Button 
                size="small" 
                icon={<ReloadOutlined />}
                onClick={isConnected ? disconnect : connect}
              >{isConnected ? 'Disconnected' : 'Connected'}</Button>
            </Space>
          </Card>
        </Col> */}

        {/* StatisticsInfo */}
        <Col span={6}>
          <Card size="small">
            <Statistic
              title=" tasksTotal"
              value={tasks.length}
              valueStyle={{ color: '#1890ff' }}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card size="small">
            <Statistic
              title="LoadStatus"
              value={loading ? 'Loading' : 'Completed'}
              valueStyle={{ color: loading ? '#52c41a' : '#999' }}
            />
          </Card>
        </Col>
        {/* WebSocket connection StatusDisabled */}
        {/* <Col span={6}>
          <Card size="small">
            <Statistic
              title="ConnectionStatus"
              value={isConnected ? 'Connected' : 'Not connected'}
              valueStyle={{ color: isConnected ? '#722ed1' : '#ff4d4f' }}
            />
          </Card>
        </Col> */}
        <Col span={6}>
          <Card size="small">
            <Statistic
              title="Unread Notifications"
              value={unreadCount}
              valueStyle={{ color: unreadCount > 0 ? '#ff4d4f' : '#999' }}
            />
          </Card>
        </Col>

        {/*  tasksProgress */}
        <Col span={12}>
          <Card 
            title=" tasksProgress" 
            size="small"
            extra={
              <Button size="small" onClick={() => setTasks([])}>ClearEmpty</Button>
            }
          >
            <div style={{ maxHeight: 300, overflowY: 'auto' }}>
              {tasks.length === 0 ? (
                <div style={{ textAlign: 'center', padding: 20, color: '#999' }}>
                  NoTask
                </div>
              ) : (
                tasks.map((task) => (
                  <TaskProgressDisplay 
                    key={task.id} 
                    taskId={task.id} 
                    userId={task.project_id || userId} // Use projectsID ofTask, if not use userId as fallback
                  />
                ))
              )}
            </div>
          </Card>
        </Col>

        {/* NotificationsList */}
        <Col span={12}>
          <NotificationList
            notifications={notifications}
            unreadCount={unreadCount}
            onMarkAsRead={markAsRead}
            onRemove={removeNotification}
            onMarkAllAsRead={markAllAsRead}
            onClearAll={clearAllNotifications}
            maxHeight={300}
          />
        </Col>
      </Row>
    </div>
  );
}; 