// Bilibili category/partition list (main categories from the official API)
export const BILIBILI_PARTITIONS = [
  { id: 1, name: "Animation" },
  { id: 4, name: "Gaming" },
  { id: 8, name: "Memes/Fan-dubs" },
  { id: 3, name: "Music" },
  { id: 129, name: "Dance" },
  { id: 181, name: "Film & TV" },
  { id: 5, name: "Entertainment" },
  { id: 36, name: "Knowledge" },
  { id: 188, name: "Tech & Gadgets" },
  { id: 202, name: "News" },
  { id: 76, name: "Food" },
  { id: 138, name: "Short Drama" },
  { id: 176, name: "Automotive" },
  { id: 155, name: "Fashion & Beauty" },
  { id: 235, name: "Sports" },
  { id: 75, name: "Animals" },
  { id: 21, name: "Vlog" },
  { id: 162, name: "Art & Drawing" },
  { id: 207, name: "Artificial Intelligence" },
  { id: 208, name: "Home & Real Estate" },
  { id: 209, name: "Outdoor & Lifestyle" },
  { id: 164, name: "Fitness" },
  { id: 161, name: "Crafts" },
  { id: 165, name: "Travel" },
  { id: 158, name: "Rural Life" },
  { id: 159, name: "Parenting" },
  { id: 160, name: "Health" },
  { id: 163, name: "Relationships" },
  { id: 22, name: "Lifestyle" },
  { id: 23, name: "Life Tips" }
]
